// ── Shared View workspace ──
// Loaded BEFORE app.js on every /shared/ page. It selects the workspace and (optionally) supplies
// that workspace's own data. With WS_DATA empty, app.js gives Shared View an independent deep
// *clone* of the MediaWatch datasets. Provide arrays here to make Shared View diverge.
window.WS = 'shared';
window.WS_DATA = {
  // Social media mentions for the Shared View → Mentions table + post preview.
  // platform must match a key in SOCIAL_PLATFORMS (app.js): facebook | twitter | instagram | youtube | reddit | tiktok
  // url = the original post permalink (used to build the live embed; falls back to a "View Post" card)
  socialMentions: [
    {reach:'494',   engScore:31, type:'Text',  platform:'twitter',   sentiment:'neutral',  influencer:'@ofc_iwant',      match:96,      followers:'1,204K', influencerScore:'28', keywords:[['itsshowtime',1],['iwanttfc',1]], entities:['iWantTFC','It\'s Showtime','BGYO','ABS-CBN'], url:'https://x.com/ofc_iwant/status/2071128073232379914', time:'09:12 AM', post:'@itsShowtimeNa @BGYO_Gelo Enjoy #ItsShowtime at iba pang Kapamilya shows on iWantTFC!',                 date:'June 28, 2026', ago:'18 hours ago'},
    {reach:'-',     engScore:55, type:'Photo', platform:'facebook',  sentiment:'positive', influencer:'@DITOphofficial', match:91, followers:'2,000K', influencerScore:'00', keywords:[['dito app',1]], entities:['DITO Telecommunity','Austrian Grand Prix','FLEXPlan 888'], thumb:'https://picsum.photos/seed/dito-f1/720/440', url:'https://www.facebook.com/DITOphofficial/posts/pfbid0Gt781pPj2adoxunsXbcRWNhtFqanvmcW5uCioHABr1mNUXdcY6rTeyExf5mjAwbMl', time:'10:00 AM', post:'Stream the Austrian Grand Prix live with FLEXPlan 888 SIMOnly. Never miss a moment with UNLI 5G for the first 12 months, 40GB AllAccess Data, unlimited calls & texts to all networks. 🏎️',  date:'June 28, 2026', ago:'21 hours ago'},
    {reach:'157',   engScore:1,  type:'Photo', platform:'facebook',  sentiment:'positive', influencer:'@wazzupph',       match:84,       followers:'860K',   influencerScore:'12', keywords:[['dito',1],['champions',1]], entities:['DITO Telecommunity','Wazzup Pilipinas'], thumb:'https://picsum.photos/seed/dito-champ/720/440', url:'https://www.facebook.com/wazzupph/posts/pfbid0Sample2WazzupChampions', time:'08:30 AM', post:'Three championships. One unstoppable team. One unwavering partner. DITO stands with the champions. 🏆',  date:'June 28, 2026', ago:'22 hours ago'},
    {reach:'1k',    engScore:2,  type:'Photo', platform:'facebook',  sentiment:'negative', influencer:'@Memory.ph',      match:82,      followers:'320K',   influencerScore:'08', keywords:[['net',1],['delay',1]], entities:['Memory PH'], thumb:'https://picsum.photos/seed/memory-net/720/440', url:'https://www.facebook.com/Memory.ph/posts/pfbid0Sample3MemorySlowNet', time:'07:45 AM', post:'Sorry mga boss mabagal net natin delay na mga upload natin na video. Dahan-dahan lang tayo. 🙏',         date:'June 28, 2026', ago:'23 hours ago'},
    {reach:'42.3k', engScore:78, type:'Photo', platform:'instagram', sentiment:'positive', influencer:'@techreviewph',   match:79,   followers:'512K',   influencerScore:'64', keywords:[['dito',1],['pocket wifi',1],['speed test',1]], entities:['DITO Telecommunity','TechReview PH','Pocket WiFi'], thumb:'https://picsum.photos/seed/dito-pocketwifi/720/440', url:'https://www.instagram.com/p/DaCKhpeFH92/', time:'02:15 PM', post:'Unboxing the latest DITO pocket WiFi — speed test results are wild! Full review on the blog. 📶',        date:'June 27, 2026', ago:'1 day ago'},
    {reach:'128k',  engScore:91, type:'Video', platform:'youtube',   sentiment:'neutral',  influencer:'@GadgetPilipinas', match:76, followers:'1,870K', influencerScore:'82', keywords:[['5g',2],['speed test',1],['telco',1]], entities:['DITO Telecommunity','Globe Telecom','Smart Communications','Metro Manila'], thumb:'https://img.youtube.com/vi/AQek1hXaJxA/hqdefault.jpg', url:'https://www.youtube.com/watch?v=AQek1hXaJxA', time:'11:00 AM', post:'DITO vs Globe vs Smart 5G speed test 2026 — which telco wins in Metro Manila? Watch till the end.',      date:'June 27, 2026', ago:'1 day ago'},
    {reach:'8.9k',  engScore:44, type:'Text',  platform:'reddit',    sentiment:'positive', influencer:'@u/ph_telcos',    match:73,    followers:'47K',    influencerScore:'39', keywords:[['dito',1],['visayas',1],['speeds',1]], entities:['DITO Telecommunity','Visayas'], url:'https://www.reddit.com/r/Philippines/comments/1abcde2/dito_speeds_after_visayas_hub/', time:'06:20 PM', post:'Anyone else getting way faster DITO speeds after the Visayas data hub launch? Posting my numbers below.', date:'June 27, 2026', ago:'1 day ago'},
    {reach:'310k',  engScore:96, type:'Video', platform:'tiktok',    sentiment:'positive', influencer:'@itsmevince',     match:71,     followers:'3,420K', influencerScore:'93', keywords:[['dito',1],['5g',1],['fyp',1]], entities:['DITO Telecommunity'], thumb:'https://picsum.photos/seed/dito-tiktok/640/780', url:'https://www.tiktok.com/@itsmevince/video/7300000000000000001', time:'09:05 PM', post:'POV: your DITO SIM finally gets 5G in the province 😭🔥 #DITO #5G #fyp',                                  date:'June 26, 2026', ago:'2 days ago'},
    {reach:'2.4k',  engScore:12, type:'Text',  platform:'twitter',   sentiment:'positive', influencer:'@juanationph',    match:68,    followers:'98K',    influencerScore:'21', keywords:[['telco',1],['prices',1]], entities:['DITO Telecommunity','Globe Telecom','PLDT'], url:'https://twitter.com/juanationph/status/1799000000000000002', time:'01:40 PM', post:'Telco war update: prices dropping fast. Good time to be a Filipino consumer. 📉 #telco',                date:'June 26, 2026', ago:'2 days ago'},
    {reach:'56.1k', engScore:67, type:'Photo', platform:'instagram', sentiment:'neutral',  influencer:'@cebufoodie',     match:67,     followers:'604K',   influencerScore:'58', keywords:[['dito',1],['cebu',1],['sponsored',1]], entities:['DITO Telecommunity','Cebu'], thumb:'https://picsum.photos/seed/dito-cebu/720/440', url:'https://www.instagram.com/p/C8sampleCebuBB/', time:'12:10 PM', post:'Sponsored by DITO — fast uploads even from the mountains of Cebu. Swipe for the view! ⛰️',              date:'June 25, 2026', ago:'3 days ago'},
    {reach:'4.7k',  engScore:23, type:'Photo', platform:'facebook',  sentiment:'positive', influencer:'@MindanaoNow',    match:64,    followers:'410K',   influencerScore:'31', keywords:[['dito',1],['wifi',1],['mindanao',1]], entities:['DITO Telecommunity','Mindanao'], thumb:'https://picsum.photos/seed/dito-mindanao/720/440', url:'https://www.facebook.com/MindanaoNow/posts/pfbid0Sample4MindanaoWifi', time:'03:25 PM', post:'DITO rolls out free public WiFi in 12 more LGUs across Mindanao. Full list in comments. 📡',            date:'June 25, 2026', ago:'3 days ago'},
    {reach:'19.2k', engScore:38, type:'Video', platform:'youtube',   sentiment:'negative', influencer:'@PinoyTechTips',  match:61,  followers:'1,120K', influencerScore:'70', keywords:[['dito',1],['switch',1],['guide',1]], entities:['DITO Telecommunity','Pinoy Tech Tips'], thumb:'https://img.youtube.com/vi/9bZkp7q19f0/hqdefault.jpg', url:'https://www.youtube.com/watch?v=9bZkp7q19f0', time:'10:30 AM', post:'How to switch to DITO and keep your number in 5 minutes — step by step guide for 2026.',                date:'June 24, 2026', ago:'4 days ago'}
  ]
};
